"""ORM models, split by domain. Import from ``app.models`` as before."""

from __future__ import annotations

from app.db import Base

from app.models.auth import (
    UserRole,
    UserPermissionCategory,
    User,
    RoundcubeSsoTokenUse,
    PasswordResetToken,
    AuthRateLimitEntry,
    WebAuthnChallenge,
    WebAuthnCredential,
)

from app.models.calendar import (
    UserCalendar,
    UserCalendarShare,
    UserCalendarSubscription,
    UserCalendarCategory,
    CalendarEventCategory,
    CalendarEventEmailAlertSubscription,
    CalendarEventNotificationSent,
)

from app.models.case_matter import (
    MatterHeadType,
    MatterSubType,
    MatterSubTypeMenu,
    CaseStatus,
    CaseLockMode,
    CaseAccessMode,
    MatterContactTypeConfig,
    Case,
    CaseSource,
    CaseQuoteSnapshot,
    CaseReferenceCounter,
    CasePropertyDetails,
    CaseAccessRule,
)

from app.models.firm import (
    LetterheadStyle,
    PrecedentKind,
    PrecedentCategory,
    FirmSettings,
    ReconciliationStatus,
    ClientAccountReconciliation,
    MergeCodeCatalog,
    Precedent,
    EmailIntegrationSettings,
    SmtpNotificationSettings,
)

from app.models.fee_scale import (
    FeeScale,
    UserFeeScaleFavorite,
    FeeScaleLineKind,
    FeeScaleAmountKind,
    FeeScaleVatTreatment,
    FeeScaleCategory,
    FeeScaleBandSet,
    FeeScaleBandRow,
    FeeScaleLine,
)

from app.models.portal_contact import (
    ContactType,
    Contact,
    ContactPortalAccess,
    MatterPortalAccess,
    ContactPortalGrant,
    CasePortalStaffRecipient,
    PortalActivityEvent,
    QuotePortalDeliveryStatus,
    QuotePortalDelivery,
    PortalLoginOtp,
    MailPluginAuthCode,
    CaseContact,
    CaseDocsView,
)

from app.models.portal_forms import (
    PortalFormFieldType,
    PortalFormSubmissionStatus,
    PortalFormTemplate,
    PortalFormTemplateField,
    PortalFormSubmission,
)

from app.models.files_tasks import (
    FileCategory,
    File,
    FileEditSession,
    AuditEvent,
    CaseNote,
    CaseTaskStatus,
    CaseTaskPriority,
    MatterSubTypeStandardTask,
    CaseTask,
    CaseTimeEntryStatus,
    CaseTimeEntry,
)

from app.models.ledger import (
    LedgerAccountType,
    LedgerDirection,
    LedgerAccount,
    LedgerEntry,
)

from app.models.finance import (
    FinanceCategoryTemplate,
    FinanceItemTemplate,
    FinanceCategory,
    FinanceItem,
)

from app.models.events import (
    MatterSubTypeEventTemplate,
    CaseEvent,
)

from app.models.invoice import (
    InvoiceSeq,
    BillingSettings,
    BillingLineTemplate,
    CaseInvoice,
    CaseInvoiceLine,
)

from app.models.signing import (
    DocusignDocumentTier,
    DocusignSignatureLevel,
    DocusignSigningStatus,
    DocusignRecipientStatus,
    DocusignIntegrationSettings,
    DocusignSigningRequest,
    DocusignSigningRecipient,
    CanarySignStatus,
    CanarySignRecipientStatus,
    CanarySignOrderMode,
    CanarySignFieldType,
    CanarySignAuditEventType,
    CanarySignRequest,
    CanarySignRecipient,
    CanarySignField,
    CanarySignAuditEvent,
)

__all__ = [
    'Base',
    'UserRole',
    'UserPermissionCategory',
    'User',
    'RoundcubeSsoTokenUse',
    'PasswordResetToken',
    'AuthRateLimitEntry',
    'WebAuthnChallenge',
    'WebAuthnCredential',
    'UserCalendar',
    'UserCalendarShare',
    'UserCalendarSubscription',
    'UserCalendarCategory',
    'CalendarEventCategory',
    'CalendarEventEmailAlertSubscription',
    'CalendarEventNotificationSent',
    'MatterHeadType',
    'MatterSubType',
    'MatterSubTypeMenu',
    'CaseStatus',
    'CaseLockMode',
    'CaseAccessMode',
    'MatterContactTypeConfig',
    'Case',
    'CaseSource',
    'CaseQuoteSnapshot',
    'CaseReferenceCounter',
    'CasePropertyDetails',
    'CaseAccessRule',
    'LetterheadStyle',
    'PrecedentKind',
    'PrecedentCategory',
    'FirmSettings',
    'ReconciliationStatus',
    'ClientAccountReconciliation',
    'MergeCodeCatalog',
    'Precedent',
    'EmailIntegrationSettings',
    'SmtpNotificationSettings',
    'FeeScale',
    'UserFeeScaleFavorite',
    'FeeScaleLineKind',
    'FeeScaleAmountKind',
    'FeeScaleVatTreatment',
    'FeeScaleCategory',
    'FeeScaleBandSet',
    'FeeScaleBandRow',
    'FeeScaleLine',
    'ContactType',
    'Contact',
    'ContactPortalAccess',
    'MatterPortalAccess',
    'ContactPortalGrant',
    'CasePortalStaffRecipient',
    'PortalActivityEvent',
    'QuotePortalDeliveryStatus',
    'QuotePortalDelivery',
    'PortalLoginOtp',
    'MailPluginAuthCode',
    'CaseContact',
    'CaseDocsView',
    'PortalFormFieldType',
    'PortalFormSubmissionStatus',
    'PortalFormTemplate',
    'PortalFormTemplateField',
    'PortalFormSubmission',
    'FileCategory',
    'File',
    'FileEditSession',
    'AuditEvent',
    'CaseNote',
    'CaseTaskStatus',
    'CaseTaskPriority',
    'MatterSubTypeStandardTask',
    'CaseTask',
    'CaseTimeEntryStatus',
    'CaseTimeEntry',
    'LedgerAccountType',
    'LedgerDirection',
    'LedgerAccount',
    'LedgerEntry',
    'FinanceCategoryTemplate',
    'FinanceItemTemplate',
    'FinanceCategory',
    'FinanceItem',
    'MatterSubTypeEventTemplate',
    'CaseEvent',
    'InvoiceSeq',
    'BillingSettings',
    'BillingLineTemplate',
    'CaseInvoice',
    'CaseInvoiceLine',
    'DocusignDocumentTier',
    'DocusignSignatureLevel',
    'DocusignSigningStatus',
    'DocusignRecipientStatus',
    'DocusignIntegrationSettings',
    'DocusignSigningRequest',
    'DocusignSigningRecipient',
    'CanarySignStatus',
    'CanarySignRecipientStatus',
    'CanarySignOrderMode',
    'CanarySignFieldType',
    'CanarySignAuditEventType',
    'CanarySignRequest',
    'CanarySignRecipient',
    'CanarySignField',
    'CanarySignAuditEvent',
]
